fix: error when uploading results due to bad request
```log
 Error: Error on uploading results: Bad request. Body:
 {"message":"The execution.start time must be at least 1732623290. (and 1 more error)","errors":{"execution.start_time":["The execution.start time must be at least 1732623290."],"execution.end_time":["The execution.end time must be at least 1732623290."]}}
```